global:
  # Opções globais para todos os receivers do slack
  slack_api_url: 'your_slack_url'
  resolve_timeout: 2m

route:
  receiver: 'slack-notifications'
  group_by: 
    - alertname
    - severity

receivers:
- name: 'slack-notifications'
  slack_configs:
  - send_resolved: true
    channel: 'prometheus-python-app'
    icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
    username: 'AlertManager'
    title: '[ {{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
    text: '*Alert:* {{ .CommonAnnotations.summary }} - {{ .CommonLabels.severity }} {{ printf "\n" }}*Description:* {{ .CommonAnnotations.description }}' 

