global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - timeout: "10s"
      static_configs:
        - targets: ["alertmanager:9093"]


rule_files:
  - "/usr/local/etc/prometheus/rules/recording-rules.yaml"
  - "/usr/local/etc/prometheus/rules/alerting-rules.yaml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
    
  - job_name: grafana
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: jjba
    static_configs:
      - targets: ["jjba:5000"]

  
