groups:
  - name: python-app
    rules:

    ## Warning
    - alert: AppLatencyBetween1and2
      expr: 1 < job:http_request_latency:rate5m < 2
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: '{{ $labels.job }} latency between one and two seconds'
        description: 'Atenção, a latência entre as requisições está entre 1 e 2 segundos'

    - alert: ManyRequestsForResponse
      expr: floor(avg_over_time(http_request_in_progress[5m])) > 5
      for: 1m
      labels:
        severity: warning  
      annotations:
        summary: '{{ $labels.job }} processing many requests'
        description: 'Atenção, estão sendo realizadas mais de 5 requisições simultaneamente'

    ## Danger
    - alert: MoreExceptionsThenSuccess
      expr: sum(http_requests_total) < http_exceptions_total
      for: 1m
      labels:    
        severity: danger
      annotations:
        summary: '{{ $labels.job }} response more exceptions then success'
        description: 'Perigo, a aplicação está respondendo mais erros do que requisições bem sucedidas'

    - alert: AppLatencyAbove2sec
      expr: job:http_request_latency:rate5m >= 2
      for: 5m
      labels:
        severity: danger
      annotations:
        summary: '{{ $labels.job }} latency above two seconds'
        description: 'Perigo, a latência entre as requisições ultrapassou 2 segundos'

    ## Critical

    - alert: InstanceIsDown
      expr: up{instance="jjba:5000"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: '{{ $labels.job }} app down'
        description: 'Erro, a aplicação não está em execução por pelo menos 5 minutos'


