{
 "title": "Python App (Exemplo)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total de requisições",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "job:http_requests_total:sum", "legendFormat": "{{app_name}}" }
   ]
  },
  {
   "title": "Requisições em andamento",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_request_in_progress", "legendFormat": "{{app_name}}" }
   ]
  },
  {
   "title": "Taxa de requisições",
   "type": "stat",
   "description": "Taxa de requisições por segundo\n",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "job:http_requests_total:sum_rate5m",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "Tempo médio entre requisições",
   "type": "stat",
   "description": "Latência média entre requisições em segundos",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "job:http_request_latency:rate5m",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "Total de Exceções",
   "type": "stat",
   "description": "Contabiliza quantas exceções ocorreram",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_exceptions_total", "legendFormat": "{{app_name}}" }
   ]
  },
  {
   "title": "Requisições por página",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "{{endpoint}}" }
   ]
  }
 ]
}